# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robin Fox Portfolio
email: robinfoxin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Aspiring web designer and developer, specialising in HTML, CSS and Javascript.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mrkitsune.com" # the base hostname & protocol for your site
twitter_username: smugfox
github_username:  smugfox
dribbble_username: smugfox

permalink: /:categories/:title

links:
  - title: about
    url: /about
  - title: projects
    url: /projects

# Build settings
markdown: kramdown

gems:
  - octopress-autoprefixer
gems: [jekyll/responsive_image]

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 350
      quality: 80
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
      quality: 90
    - width: 1024
      quality: 90
    - width: 1400
      quality: 90

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: img/resized/%{width}/%{filename}-%{width}x%{height}.%{extension}
